server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ws_music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.ws.musicserver.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      javaclimb:
        music:
          dao: debug